name: styld_stylist
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.4
  bulleted_list: ^0.0.1+0.1a
  calendar_timeline: ^1.0.3-null-safety.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  date_picker_timeline:
  dotted_border:
  flutter:
    sdk: flutter
  flutter_screenutil: 
  flutter_staggered_grid_view:
  flutter_svg: 
  flutter_svg_provider:
  # get: ^4.3.8
  google_fonts:
  image_picker:
  intl: any
  introduction_screen:
  pinput: ^5.0.0
  provider:
  syncfusion_flutter_datepicker:
  syncfusion_flutter_sliders:
  timelines:
  # record_mp3: ^3.0.0
  # audioplayers: ^0.20.1
  permission_handler:
  # path_provider: ^2.0.9
  photo_view: ^0.15.0

dev_dependencies:
  cloud_firestore:
  connectivity_plus:
  device_info:
  dio:
  file_picker:
  firebase_auth:
  firebase_core: 
  firebase_messaging: 
  firebase_storage: 
  flutter_local_notifications:
  flutter_test:
    sdk: flutter
  geocoding:
  geolocator:
  get:
  get_it: any
  google_maps_flutter:
  heic_to_jpg:
  # logger: ^1.1.0
  modal_progress_hud_nsn: ^0.5.1
  rxdart: 
  shared_preferences:
  url_launcher: any
  rename:
  flutter_rating_bar:
  timeago:
  firebase_database:
  flutter_stripe:
  http: 
  flutter_polyline_points:

  flutter_launcher_icons: ^0.13.1

### app icon
flutter_icons:
  image_path: "assets/icon/icon.png" 
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/icons/
    # - assets/fonts/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
