import 'package:styld_stylist/core/model/schedule_order_model.dart';

final List<ScheduleOrderModel> scheduleOrderLists = [
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Marry Angel",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Julien Queen",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Marry Angel",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Julien Queen",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Marry Angel",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Julien Queen",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Marry Angel",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Julien Queen",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Marry Angel",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Julien Queen",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Marry Angel",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
  ScheduleOrderModel(
    address: "23 St, Mall Road Near Ware House, New York",
    date: "October 20",
    duration: "1hr & 30 Min",
    name: "Julien Queen",
    price: "50",
    time: " 12:00 PM",
    path: "assets/images/mask_Group_89.png",
  ),
];
