import 'package:styld_stylist/core/constants/images.dart';
import 'package:styld_stylist/core/model/active_stylist_model.dart';
import 'package:styld_stylist/core/model/stylist_approval_model.dart';

final List<ActiveStylistModel> activeStylistData = [
  ActiveStylistModel(
      likeCount: '34',
      address: '23 St, Mall Road Near Ware House, New York',
      title: 'Olevia Beauty Saloon & MakeUp',
      imageUrl: StyldImages.hairDresser,
      name: 'Sophia Amelia',
      mondayThursdayTimings: '09:00 AM - 12:00 PM',
      fridaySaturdayTimings: '01:00 PM - 10:00 PM',
      description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis magna justo, scelerisque et euismod sit amet, eifend quis magna. Sed fringilla, est at volutpat sodales, nisl eros t tique sapien, ut gravida urna lorem a odio.',
      mobile: '+1 (911) 111-11-11',
      dob: '11.05.1995',
      email: 'stylduser@gmail.com',
      gender: 'Male',
      service: 'Beauty Salon',
      rating: '4.9'),
  ActiveStylistModel(
      likeCount: '34',
      address: '23 St, Mall Road Near Ware House, New York',
      title: 'Olevia Beauty Saloon & MakeUp',
      imageUrl: StyldImages.hairDresser,
      name: 'Sophia Amelia',
      mondayThursdayTimings: '09:00 AM - 12:00 PM',
      fridaySaturdayTimings: '01:00 PM - 10:00 PM',
      description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis magna justo, scelerisque et euismod sit amet, eifend quis magna. Sed fringilla, est at volutpat sodales, nisl eros t tique sapien, ut gravida urna lorem a odio.',
      mobile: '+1 (911) 111-11-11',
      dob: '11.05.1995',
      email: 'stylduser@gmail.com',
      gender: 'Male',
      service: 'Beauty Salon',
      rating: '4.9'),
  ActiveStylistModel(
      likeCount: '34',
      address: '23 St, Mall Road Near Ware House, New York',
      title: 'Olevia Beauty Saloon & MakeUp',
      imageUrl: StyldImages.hairDresser,
      name: 'Sophia Amelia',
      mondayThursdayTimings: '09:00 AM - 12:00 PM',
      fridaySaturdayTimings: '01:00 PM - 10:00 PM',
      description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis magna justo, scelerisque et euismod sit amet, eifend quis magna. Sed fringilla, est at volutpat sodales, nisl eros t tique sapien, ut gravida urna lorem a odio.',
      mobile: '+1 (911) 111-11-11',
      dob: '11.05.1995',
      email: 'stylduser@gmail.com',
      gender: 'Male',
      service: 'Beauty Salon',
      rating: '4.9'),
  ActiveStylistModel(
      likeCount: '34',
      address: '23 St, Mall Road Near Ware House, New York',
      title: 'Olevia Beauty Saloon & MakeUp',
      imageUrl: StyldImages.hairDresser,
      name: 'Sophia Amelia',
      mondayThursdayTimings: '09:00 AM - 12:00 PM',
      fridaySaturdayTimings: '01:00 PM - 10:00 PM',
      description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis magna justo, scelerisque et euismod sit amet, eifend quis magna. Sed fringilla, est at volutpat sodales, nisl eros t tique sapien, ut gravida urna lorem a odio.',
      mobile: '+1 (911) 111-11-11',
      dob: '11.05.1995',
      email: 'stylduser@gmail.com',
      gender: 'Male',
      service: 'Beauty Salon',
      rating: '4.9'),
  ActiveStylistModel(
      likeCount: '34',
      address: '23 St, Mall Road Near Ware House, New York',
      title: 'Olevia Beauty Saloon & MakeUp',
      imageUrl: StyldImages.hairDresser,
      name: 'Sophia Amelia',
      mondayThursdayTimings: '09:00 AM - 12:00 PM',
      fridaySaturdayTimings: '01:00 PM - 10:00 PM',
      description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis magna justo, scelerisque et euismod sit amet, eifend quis magna. Sed fringilla, est at volutpat sodales, nisl eros t tique sapien, ut gravida urna lorem a odio.',
      mobile: '+1 (911) 111-11-11',
      dob: '11.05.1995',
      email: 'stylduser@gmail.com',
      gender: 'Male',
      service: 'Beauty Salon',
      rating: '4.9'),
];
final List<StylistApprovalModel> stylistApprovalData = [
  StylistApprovalModel(
      title: 'Olevia Beauty Saloon & MakeUp',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '20',
      imageUrl: StyldImages.hairDresser,
      premiumPackagePrice: '40',
      standardPackagePrice: '70'),
  StylistApprovalModel(
      title: 'Scarlet Johnson Nail Polisher',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '10',
      imageUrl: StyldImages.hairDresser2,
      premiumPackagePrice: '30',
      standardPackagePrice: '50'),
  StylistApprovalModel(
      title: 'Scarlet Johnson Nail Polisher',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '10',
      imageUrl: StyldImages.hairDresser2,
      premiumPackagePrice: '30',
      standardPackagePrice: '50'),
  StylistApprovalModel(
      title: 'Olevia Beauty Saloon & MakeUp',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '20',
      imageUrl: StyldImages.hairDresser,
      premiumPackagePrice: '40',
      standardPackagePrice: '70'),
  StylistApprovalModel(
      title: 'Scarlet Johnson Nail Polisher',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '10',
      imageUrl: StyldImages.hairDresser2,
      premiumPackagePrice: '30',
      standardPackagePrice: '50'),
  StylistApprovalModel(
      title: 'Olevia Beauty Saloon & MakeUp',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '20',
      imageUrl: StyldImages.hairDresser,
      premiumPackagePrice: '40',
      standardPackagePrice: '70'),
  StylistApprovalModel(
      title: 'Scarlet Johnson Nail Polisher',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '10',
      imageUrl: StyldImages.hairDresser2,
      premiumPackagePrice: '30',
      standardPackagePrice: '50'),
  StylistApprovalModel(
      title: 'Olevia Beauty Saloon & MakeUp',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '20',
      imageUrl: StyldImages.hairDresser,
      premiumPackagePrice: '40',
      standardPackagePrice: '70'),
  StylistApprovalModel(
      title: 'Scarlet Johnson Nail Polisher',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '10',
      imageUrl: StyldImages.hairDresser2,
      premiumPackagePrice: '30',
      standardPackagePrice: '50'),
  StylistApprovalModel(
      title: 'Olevia Beauty Saloon & MakeUp',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '20',
      imageUrl: StyldImages.hairDresser,
      premiumPackagePrice: '40',
      standardPackagePrice: '70'),
  StylistApprovalModel(
      title: 'Scarlet Johnson Nail Polisher',
      address: '23 St, Mall Road Near Ware House, New York',
      basicPackagePrice: '10',
      imageUrl: StyldImages.hairDresser2,
      premiumPackagePrice: '30',
      standardPackagePrice: '50'),
];
