import 'package:styld_stylist/core/constants/images.dart';
import 'package:styld_stylist/core/model/stylist_order_approval_model.dart';

final List<StylistOrderApprovalModel> stylistOrderApprovalList = [
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
  StylistOrderApprovalModel(
    name: 'Mary Angel',
    rating: '5.0',
    date: 'October 20',
    duration: '1hr & 30 Min',
    time: '12:00 PM',
    service: 'Make up & Nail Polishing',
    shortAddress: '#123, 3rd Floor',
    price: '30 (Standard Package)',
    address: '23 St, Mall Road Near Ware House, New York',
    imageUrl: StyldImages.hairDresser,
  ),
];
